// deno-lint-ignore-file no-console
/**
 * CLI Deploy Command Implementation - Deployment scaffold generator
 *
 * Generates project-level deployment artifacts: Dockerfiles, compose files,
 * systemd units, and environment variable templates.
 */

export interface DeployOptions {
  format: string;
  output?: string;
}

export const VALID_FORMATS = ["docker", "compose", "systemd", "env"] as const;

export type DeployFormat = typeof VALID_FORMATS[number];

export class DeployCommand {
  /**
   * Validate that the format string is one of VALID_FORMATS.
   * Throws an error listing valid formats if invalid.
   */
  validateFormat(format: string): void {
    if (!(VALID_FORMATS as readonly string[]).includes(format)) {
      throw new Error(
        `Invalid format: "${format}". Valid formats: ${
          VALID_FORMATS.join(", ")
        }`,
      );
    }
  }

  /**
   * Resolve the output directory path.
   * Defaults to "./deploy" if not specified.
   */
  resolveOutputDir(output: string | undefined): string {
    return output || "./deploy";
  }

  /**
   * Try to read the project name from disc.toml.
   * Returns "disc" as a fallback.
   */
  private async readProjectName(): Promise<string> {
    try {
      const configFile = await Deno.readTextFile("disc.toml");
      const match = configFile.match(/name\s*=\s*"([^"]+)"/);
      if (match) return match[1];
    } catch {
      // Ignore errors — disc.toml is optional
    }
    return "disc";
  }

  /**
   * Generate a Dockerfile for running Disc.
   */
  generateDockerfile(projectName: string): string {
    return `# Dockerfile for ${projectName}
# Generated by: disc deploy --format docker

FROM denoland/deno:latest

WORKDIR /app

# Copy dependency manifests first for better caching
COPY deno.json deno.lock* ./

# Cache dependencies
RUN deno cache --reload cli/main.ts 2>/dev/null || true

# Copy source
COPY . .

# Cache the main entry point
RUN deno cache cli/main.ts

# Expose the default Disc port
EXPOSE 5656

# Use DATABASE_URL for external PostgreSQL connection
ENV DATABASE_URL=""
ENV DISC_HOST="0.0.0.0"
ENV DISC_PORT="5656"

CMD ["deno", "run", "--allow-net", "--allow-read", "--allow-write", "--allow-env", "--allow-run", "cli/main.ts", "serve"]
`;
  }

  /**
   * Generate a docker-compose.yml with Disc and PostgreSQL services.
   */
  generateCompose(projectName: string): string {
    return `# docker-compose.yml for ${projectName}
# Generated by: disc deploy --format compose

services:
  disc:
    build: .
    ports:
      - "5656:5656"
    environment:
      DATABASE_URL: "postgresql://disc:$\{POSTGRES_PASSWORD}@postgres:5432/${projectName}"
      DISC_HOST: "0.0.0.0"
      DISC_PORT: "5656"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: disc
      # NEVER deploy with a hardcoded password. Set POSTGRES_PASSWORD
      # in .env.production (see 'disc deploy --format env') or override
      # here before running docker compose up.
      POSTGRES_PASSWORD: $\{POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
      POSTGRES_DB: ${projectName}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U disc"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
`;
  }

  /**
   * Generate a systemd service unit file for Disc.
   */
  generateSystemd(projectName: string): string {
    return `# disc.service for ${projectName}
# Generated by: disc deploy --format systemd
#
# Install:
#   sudo cp disc.service /etc/systemd/system/disc.service
#   sudo systemctl daemon-reload
#   sudo systemctl enable disc
#   sudo systemctl start disc

[Unit]
Description=Disc Database Server (${projectName})
Documentation=https://github.com/systemsoft/disc
After=network.target postgresql.service
Wants=postgresql.service

[Service]
Type=simple
User=\${DISC_USER:-disc}
Group=\${DISC_GROUP:-disc}
WorkingDirectory=\${DISC_HOME:-/opt/disc}
EnvironmentFile=\${DISC_ENV_FILE:-/etc/disc/disc.env}
# Two ways to run — prefer the compiled binary for production (no Deno
# dependency), fall back to the source path for dev installs. Override
# DISC_EXEC to point at a custom path, e.g.
#   DISC_EXEC=/opt/disc/disc              # native binary
#   DISC_EXEC=/usr/bin/deno run ...       # custom deno invocation
ExecStart=\${DISC_EXEC:-/opt/disc/disc serve}
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=disc

# Security hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/opt/disc /var/lib/disc

[Install]
WantedBy=multi-user.target
`;
  }

  /**
   * Generate a .env.production template with all documented env vars.
   */
  generateEnv(projectName: string): string {
    return `# .env.production for ${projectName}
# Generated by: disc deploy --format env
#
# Copy this file and fill in your production values:
#   cp .env.production .env

# =============================================================================
# Database
# =============================================================================

# PostgreSQL connection string
DATABASE_URL="postgresql://disc:CHANGE_ME@localhost:5432/${projectName}"

# =============================================================================
# Server
# =============================================================================

# Host to bind to (use 0.0.0.0 for all interfaces)
DISC_HOST="0.0.0.0"

# Port to listen on
DISC_PORT="5656"

# =============================================================================
# Authentication
# =============================================================================

# JWT signing secret (required when auth is enabled)
# Generate with: openssl rand -base64 32
DISC_JWT_SECRET=""

# Enable the authentication system (true/false)
DISC_ENABLE_AUTH="false"

# Enable object-level access policies (requires auth)
DISC_ENABLE_ACCESS_POLICIES="false"

# =============================================================================
# Logging
# =============================================================================

# Log level: debug, info, warn, error
DISC_LOG_LEVEL="info"

# Log format: text, json
DISC_LOG_FORMAT="json"

# Slow query threshold in milliseconds
DISC_SLOW_QUERY_MS="1000"

# =============================================================================
# Rate Limiting
# =============================================================================

# Maximum requests per window
DISC_RATE_LIMIT_REQUESTS="1000"

# Rate limit window in milliseconds
DISC_RATE_LIMIT_WINDOW_MS="60000"

# =============================================================================
# Cache
# =============================================================================

# Maximum cache size in entries
DISC_CACHE_MAX_SIZE="10000"

# =============================================================================
# TLS
# =============================================================================

# Path to TLS certificate file
DISC_TLS_CERT=""

# Path to TLS private key file
DISC_TLS_KEY=""

# =============================================================================
# Metrics
# =============================================================================

# Enable Prometheus-compatible metrics endpoint
DISC_ENABLE_METRICS="false"
`;
  }

  /**
   * Determine the output file path and name for a given format.
   */
  private outputFileName(format: DeployFormat): string {
    switch (format) {
      case "docker":
        return "Dockerfile";
      case "compose":
        return "docker-compose.yml";
      case "systemd":
        return "disc.service";
      case "env":
        return ".env.production";
    }
  }

  /**
   * Generate content for a given format.
   */
  private generateContent(format: DeployFormat, projectName: string): string {
    switch (format) {
      case "docker":
        return this.generateDockerfile(projectName);
      case "compose":
        return this.generateCompose(projectName);
      case "systemd":
        return this.generateSystemd(projectName);
      case "env":
        return this.generateEnv(projectName);
    }
  }

  /**
   * Execute the deploy command.
   *
   * 1. Validate format
   * 2. Determine output directory
   * 3. Create output directory if needed
   * 4. Generate and write the deployment artifact
   * 5. Print success message
   */
  async execute(options: DeployOptions): Promise<void> {
    // Validate format
    this.validateFormat(options.format);

    const format = options.format as DeployFormat;
    const outputDir = this.resolveOutputDir(options.output);
    const projectName = await this.readProjectName();
    const fileName = this.outputFileName(format);
    const filePath = `${outputDir}/${fileName}`;

    console.log(`Generating ${format} deployment artifact...`);
    console.log(`  Project: ${projectName}`);
    console.log(`  Output: ${filePath}`);

    // Create output directory if it doesn't exist
    await Deno.mkdir(outputDir, { recursive: true });

    // Generate and write content
    const content = this.generateContent(format, projectName);
    await Deno.writeTextFile(filePath, content);

    console.log(`\nDeploy artifact generated!`);
    console.log(`  File: ${filePath}`);
  }
}

export const deployCommand = new DeployCommand();
