/**
 * Ensures auto-generated manifests exist (with empty stubs) so the
 * codebase can type-check, lint, and test without running a full build.
 *
 * `postgres/embedded-pg-manifest.ts` is git-ignored because its
 * `sourceUrl` paths shift between local (`~/.disc/postgres/...`) and
 * cross-platform (`dist/embedded-pg/<platform>/...`) staging dirs,
 * producing 5000-line per-build diffs and per-platform merge conflicts.
 * A real `disc build` overwrites the stub with the full manifest.
 *
 * Idempotent — leaves existing manifests alone. Run via `deno task prep`
 * (chained before `test`, `check`, `dev`, `serve`, `cli`, and `build`).
 */

/*** UTILITY ------------------------------------------ ***/

import { dirname, fromFileUrl, join } from "@std/path";

/*** CONSTANTS ---------------------------------------- ***/

const ROOT = dirname(dirname(fromFileUrl(import.meta.url)));

const PG_MANIFEST_STUB = `/**
 * Embedded PostgreSQL manifest.
 *
 * Auto-generated by \`cli/build.ts\` (do not edit by hand). Empty when
 * \`<DISC_HOME>/postgres/<version>/\` was absent at build time, in which
 * case the runtime falls back to the network downloader.
 *
 * Every \`sourceUrl\` here is constructed from \`import.meta.resolve()\`
 * with a path relative to this manifest file. \`deno compile --include\`
 * bakes the file into the binary; at runtime
 * \`Deno.readFile(sourceUrl)\` hits Deno’s embedded VFS because the
 * resolution flows through the module graph rather than a bare absolute
 * \`file://\` URL (which would fall through to the real filesystem and
 * fail on a different machine than the one that built the binary).
 * \`postgres/embedded-pg.ts\` writes the bytes to
 * \`<DISC_HOME>/embedded-postgres/<version>/\`.
 */

/*** UTILITY ------------------------------------------ ***/

import type { EmbeddedPgEntry } from "./embedded-extractor.ts";

/*** EXPORT ------------------------------------------- ***/

export const EMBEDDED_PG_MANIFEST: readonly EmbeddedPgEntry[] = [];

export const EMBEDDED_PG_VERSION = "16.4";\n`;

/*** MAIN --------------------------------------------- ***/

async function ensureFile(path: string, contents: string): Promise<boolean> {
  try {
    await Deno.stat(path);
    return false;
  } catch {
    /*** Missing — fall through to write. ***/
  }

  await Deno.writeTextFile(path, contents);
  return true;
}

async function main(): Promise<void> {
  const pgManifestPath = join(ROOT, "postgres", "embedded-pg-manifest.ts");
  const wrote = await ensureFile(pgManifestPath, PG_MANIFEST_STUB);

  if (wrote) {
    // deno-lint-ignore no-console
    console.log(`prep: wrote stub → ${pgManifestPath}`);
  }
}

if (import.meta.main)
  await main();
