/**
 * Embedded Disc SDK manifest.
 *
 * Auto-generated by `cli/build.ts` (do not edit by hand). Empty when
 * `<repo>/sdk/` was absent at build time.
 *
 * Every `sourceUrl` here is constructed from `import.meta.resolve()`
 * with a path relative to this manifest file. `deno compile --include`
 * bakes the file into the binary; at runtime
 * `Deno.readFile(sourceUrl)` hits Deno’s embedded VFS because the
 * resolution flows through the module graph rather than a bare absolute
 * `file://` URL (which would fall through to the real filesystem and
 * fail on a different machine than the one that built the binary).
 * `codegen/sdk-extractor.ts` then writes the bytes alongside the
 * generated client output (`<outputDir>/sdk/`).
 */

/*** UTILITY ------------------------------------------ ***/

import type { EmbeddedSdkEntry } from "./sdk-extractor.ts";

/*** EXPORT ------------------------------------------- ***/

export const EMBEDDED_SDK_MANIFEST: readonly EmbeddedSdkEntry[] = [
  { mode: 0o644, relPath: "auth.ts", sourceUrl: new URL(import.meta.resolve("../sdk/auth.ts")) },
  { mode: 0o644, relPath: "client.ts", sourceUrl: new URL(import.meta.resolve("../sdk/client.ts")) },
  { mode: 0o644, relPath: "codecs.ts", sourceUrl: new URL(import.meta.resolve("../sdk/codecs.ts")) },
  { mode: 0o644, relPath: "edgeql-ident.ts", sourceUrl: new URL(import.meta.resolve("../sdk/edgeql-ident.ts")) },
  { mode: 0o644, relPath: "errors.ts", sourceUrl: new URL(import.meta.resolve("../sdk/errors.ts")) },
  { mode: 0o644, relPath: "filter-compiler.ts", sourceUrl: new URL(import.meta.resolve("../sdk/filter-compiler.ts")) },
  { mode: 0o644, relPath: "mod.ts", sourceUrl: new URL(import.meta.resolve("../sdk/mod.ts")) },
  { mode: 0o644, relPath: "query-builder.ts", sourceUrl: new URL(import.meta.resolve("../sdk/query-builder.ts")) },
  { mode: 0o644, relPath: "schema-types.ts", sourceUrl: new URL(import.meta.resolve("../sdk/schema-types.ts")) },
  { mode: 0o644, relPath: "subscription.ts", sourceUrl: new URL(import.meta.resolve("../sdk/subscription.ts")) },
  { mode: 0o644, relPath: "transaction.ts", sourceUrl: new URL(import.meta.resolve("../sdk/transaction.ts")) },
  { mode: 0o644, relPath: "types.ts", sourceUrl: new URL(import.meta.resolve("../sdk/types.ts")) },
  { mode: 0o644, relPath: "validation.ts", sourceUrl: new URL(import.meta.resolve("../sdk/validation.ts")) }
];
