/*** SPDX-License-Identifier: Apache-2.0
     Copyright 2026 Ideas Never Cease ***/

/**
 * Embedded Disc SDK manifest.
 *
 * Auto-generated by `cli/build.ts` before each `disc build` run. Lists
 * every `sdk/*.ts` source file (excluding `*.test.ts`) that the runtime
 * extracts alongside generated client output so downstream projects
 * never need a separate `npm install` / `jsr add` for the SDK.
 *
 * Default state: empty array. With an empty manifest,
 * `extractEmbeddedSdk(...)` writes only the marker file — `disc codegen`
 * still runs, but the generated `client.ts` import (`./sdk/mod.ts`) will
 * 404 unless the user supplies the SDK themselves. This keeps `deno
 * task cli` working from a fresh clone where the build step hasn’t run.
 *
 * To rebuild the manifest:
 *   1. `deno task cli build` regenerates this file before deno compile.
 *   2. The compiled binary now ships the SDK embedded.
 *
 * The manifest contains absolute `file://` URLs from the build machine,
 * so a regenerated manifest is build-machine-specific — **do not commit
 * a regenerated manifest**. The repo always ships the empty default;
 * the build step recreates the manifest in place just for that build’s
 * compile invocation.
 */

/*** UTILITY ------------------------------------------ ***/

import type { EmbeddedSdkEntry } from "./sdk-extractor.ts";

/*** EXPORT ------------------------------------------- ***/

export const EMBEDDED_SDK_MANIFEST: readonly EmbeddedSdkEntry[] = [];
