/**
 * UI asset manifest.
 *
 * Lists every file under `ui/build/` that is bundled into the binary via
 * `deno compile --include ui/build`. Auto-generated by `cli/build.ts`
 * before each `disc build` run; do not edit by hand. To refresh:
 *
 *   bash ui/build.sh && deno task cli build
 *
 * The manifest is checked in so callers don’t need to run the build to
 * use the asset handler in tests / development.
 */

/*** EXPORT ------------------------------------------- ***/

export const UI_ASSET_MANIFEST: readonly string[] = [
  "_app/env.js",
  "_app/immutable/assets/0.BMsHEMJD.css",
  "_app/immutable/assets/10.BcPv1LmS.css",
  "_app/immutable/assets/11.RisR_9Ww.css",
  "_app/immutable/assets/2._M7p3KgU.css",
  "_app/immutable/assets/3.BCy4rwKK.css",
  "_app/immutable/assets/4.ypkmg6yk.css",
  "_app/immutable/assets/5.PsO0ahk_.css",
  "_app/immutable/assets/6.rEpqnNNL.css",
  "_app/immutable/assets/7.gHHQ5vGT.css",
  "_app/immutable/assets/8.CO9oIN7U.css",
  "_app/immutable/assets/9.eGfXH3Xa.css",
  "_app/immutable/assets/disc.CBufSZ-I.svg",
  "_app/immutable/chunks/BFYQcBYR.js",
  "_app/immutable/chunks/BMoV9LMr.js",
  "_app/immutable/chunks/B_QKZsN-.js",
  "_app/immutable/chunks/Dz1gD0Ts.js",
  "_app/immutable/chunks/I8rQr1kY.js",
  "_app/immutable/chunks/yuUCF_ae.js",
  "_app/immutable/entry/app.CS2LzVim.js",
  "_app/immutable/entry/start.BB547q34.js",
  "_app/immutable/nodes/0.DXAIJozL.js",
  "_app/immutable/nodes/1.BOGAk0m3.js",
  "_app/immutable/nodes/10.B3mF9teq.js",
  "_app/immutable/nodes/11.CDeGVV-n.js",
  "_app/immutable/nodes/2.C4cIk4HN.js",
  "_app/immutable/nodes/3.CDzfsYhn.js",
  "_app/immutable/nodes/4.CDL7Dl_o.js",
  "_app/immutable/nodes/5.CxvkUEXD.js",
  "_app/immutable/nodes/6.BPsU1uV1.js",
  "_app/immutable/nodes/7.DdhmW9DN.js",
  "_app/immutable/nodes/8.BqDm1ymn.js",
  "_app/immutable/nodes/9.BYewQSAr.js",
  "_app/version.json",
  "index.html",
  "type/tektur-variable.woff2",
  "type/tektur.woff2"
];

export const UI_ASSET_SET: ReadonlySet<string> = new Set(UI_ASSET_MANIFEST);
