/**
 * UI asset manifest.
 *
 * Lists every file under `ui/build/` that is bundled into the binary via
 * `deno compile --include ui/build`. Auto-generated by `cli/build.ts`
 * before each `disc build` run; do not edit by hand. To refresh:
 *
 *   bash ui/build.sh && deno task cli build
 *
 * The manifest is checked in so callers don’t need to run the build to
 * use the asset handler in tests / development.
 */

/*** EXPORT ------------------------------------------- ***/

export const UI_ASSET_MANIFEST: readonly string[] = [
  "_app/env.js",
  "_app/immutable/assets/0.919YUGfc.css",
  "_app/immutable/assets/10.B2h1bF-n.css",
  "_app/immutable/assets/11.RisR_9Ww.css",
  "_app/immutable/assets/2.DoMh2bhF.css",
  "_app/immutable/assets/3.B5F65cke.css",
  "_app/immutable/assets/4.CgLG11mv.css",
  "_app/immutable/assets/5.BopOCuuE.css",
  "_app/immutable/assets/6.DDvZwKcy.css",
  "_app/immutable/assets/7.DH3oWMfZ.css",
  "_app/immutable/assets/8.B6duE-Mf.css",
  "_app/immutable/assets/9.MHyk_IZH.css",
  "_app/immutable/assets/disc.CBufSZ-I.svg",
  "_app/immutable/chunks/BFYQcBYR.js",
  "_app/immutable/chunks/BKqPPALr.js",
  "_app/immutable/chunks/BfROprBo.js",
  "_app/immutable/chunks/DCan6b6N.js",
  "_app/immutable/chunks/I8rQr1kY.js",
  "_app/immutable/chunks/RhNSr_1X.js",
  "_app/immutable/entry/app.myR6LamP.js",
  "_app/immutable/entry/start.Ci6-DVyf.js",
  "_app/immutable/nodes/0.i3Bh2IDz.js",
  "_app/immutable/nodes/1.Ik_rudN1.js",
  "_app/immutable/nodes/10.CBZW7J6r.js",
  "_app/immutable/nodes/11.Beb2d8HD.js",
  "_app/immutable/nodes/2.CkCRcNE4.js",
  "_app/immutable/nodes/3.m7Dva5xC.js",
  "_app/immutable/nodes/4.mQZMDBeD.js",
  "_app/immutable/nodes/5.CnwegWds.js",
  "_app/immutable/nodes/6.CWHxfPKA.js",
  "_app/immutable/nodes/7.DUQbbCzu.js",
  "_app/immutable/nodes/8.z73m_EfL.js",
  "_app/immutable/nodes/9.Bhht7N7k.js",
  "_app/version.json",
  "index.html",
  "type/tektur-variable.woff2",
  "type/tektur.woff2"
];

export const UI_ASSET_SET: ReadonlySet<string> = new Set(UI_ASSET_MANIFEST);
