/**
 * UI asset manifest.
 *
 * Lists every file under `ui/build/` that is bundled into the binary via
 * `deno compile --include ui/build`. Auto-generated by `cli/build.ts`
 * before each `disc build` run; do not edit by hand. To refresh:
 *
 *   bash ui/build.sh && deno task cli build
 *
 * The manifest is checked in so callers don’t need to run the build to
 * use the asset handler in tests / development.
 */

/*** EXPORT ------------------------------------------- ***/

export const UI_ASSET_MANIFEST: readonly string[] = [
  "_app/env.js",
  "_app/immutable/assets/0.1foM-dAx.css",
  "_app/immutable/assets/10.BcPv1LmS.css",
  "_app/immutable/assets/11.RisR_9Ww.css",
  "_app/immutable/assets/2.CKcu47L4.css",
  "_app/immutable/assets/3.ypkmg6yk.css",
  "_app/immutable/assets/4.COH-1Dfb.css",
  "_app/immutable/assets/5.dBsppYCr.css",
  "_app/immutable/assets/6.rEpqnNNL.css",
  "_app/immutable/assets/7.gHHQ5vGT.css",
  "_app/immutable/assets/8.CO9oIN7U.css",
  "_app/immutable/assets/9.eGfXH3Xa.css",
  "_app/immutable/assets/favicon.CbSeGZBi.svg",
  "_app/immutable/chunks/BFYQcBYR.js",
  "_app/immutable/chunks/BMNGe1hU.js",
  "_app/immutable/chunks/B_QKZsN-.js",
  "_app/immutable/chunks/Dz1gD0Ts.js",
  "_app/immutable/chunks/I8rQr1kY.js",
  "_app/immutable/chunks/kJNrz6dR.js",
  "_app/immutable/chunks/yuUCF_ae.js",
  "_app/immutable/entry/app.C98zPAJr.js",
  "_app/immutable/entry/start.SH_XQIgN.js",
  "_app/immutable/nodes/0.B0LHEnhY.js",
  "_app/immutable/nodes/1.CuQvYitN.js",
  "_app/immutable/nodes/10.BjieOVwh.js",
  "_app/immutable/nodes/11._BcZQSmD.js",
  "_app/immutable/nodes/2.DCobrzC0.js",
  "_app/immutable/nodes/3.BnvKAIfU.js",
  "_app/immutable/nodes/4.BO2V2NjS.js",
  "_app/immutable/nodes/5.CSDSm12v.js",
  "_app/immutable/nodes/6.D_gN0dl0.js",
  "_app/immutable/nodes/7.Cadk8-jF.js",
  "_app/immutable/nodes/8.DQ5rGxZj.js",
  "_app/immutable/nodes/9.DBXL_Ad5.js",
  "_app/version.json",
  "index.html",
  "type/tektur-variable.woff2",
  "type/tektur.woff2"
];

export const UI_ASSET_SET: ReadonlySet<string> = new Set(UI_ASSET_MANIFEST);
