/*** SPDX-License-Identifier: Apache-2.0
     Copyright 2026 Ideas Never Cease ***/

import { join } from "@std/path";

const GENERATED_HEADER = "# PostgreSQL configuration generated by Disc";
const LOG_FILENAME = `log_filename = 'postgresql-%a.log'`;
const LOG_ROTATION_SIZE = `log_rotation_size = 0`;
const LOG_STATEMENT = `log_statement = 'ddl'`;
const LOG_TRUNCATE_ON_ROTATION = `log_truncate_on_rotation = on`;

/*** Logging lines Disc generated before 2026.09.26, mapped to their replacements. Only exact
     matches are rewritten, so a setting the user changed is left alone. ***/
const LEGACY_LOGGING_LINES: Record<string, string> = {
  "log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'": `${LOG_FILENAME}\n${LOG_TRUNCATE_ON_ROTATION}`,
  "log_rotation_size = 100MB": LOG_ROTATION_SIZE,
  "log_statement = 'all'": LOG_STATEMENT
};

/*** A weekday log file older than this holds last week's logs. PostgreSQL appends to an existing
     file when it starts (truncation only happens on a time-based rotation), so a stale file would
     otherwise keep growing across weeks. ***/
const STALE_LOG_AGE_MS = 6 * 24 * 60 * 60 * 1000;

/**
 * Remove PostgreSQL log files (`postgresql-*.log`) in `logDir` last written
 * at least six days before `now`. Run before PostgreSQL starts, so the day's
 * weekday file is started fresh and pre-cyclic timestamped files age out.
 */
export async function pruneStaleLogFiles(logDir: string, now = Date.now()): Promise<void> {
  let entries: Deno.DirEntry[];

  try {
    entries = await Array.fromAsync(Deno.readDir(logDir));
  } catch (error) {
    if (error instanceof Deno.errors.NotFound)
      return;

    throw error;
  }

  for (const entry of entries) {
    if (!entry.isFile || !/^postgresql-.*\.log$/.test(entry.name))
      continue;

    const path = join(logDir, entry.name);
    const { mtime } = await Deno.stat(path);

    if (mtime && now - mtime.getTime() >= STALE_LOG_AGE_MS)
      await Deno.remove(path);
  }
}

export interface PostgresConfigOptions {
  dataDir: string;
  maxConnections?: number;
  port?: number;
  sharedBuffers?: string;
  socketDir?: string;
  workMem?: string;
}

export class PostgresConfig {
  generate(options: PostgresConfigOptions): string {
    const {
      maxConnections = 100,
      port = 0,
      sharedBuffers = "128MB",
      socketDir,
      workMem = "4MB"
    } = options;

    const lines: string[] = [
      GENERATED_HEADER,
      "# https://github.com/nickel/disc",
      "",
      "# Connection Settings",
      `listen_addresses = ''  # Unix socket only by default`,
      `port = ${port === 0 ? 5432 : port}  # Default port for socket file naming`,
      `max_connections = ${maxConnections}`,
      `superuser_reserved_connections = 3`
    ];

    if (socketDir) {
      lines.push(`unix_socket_directories = '${socketDir}'`);
    }

    lines.push(
      "",
      "# Memory Settings",
      `shared_buffers = ${sharedBuffers}`,
      `work_mem = ${workMem}`,
      `maintenance_work_mem = 64MB`,
      `effective_cache_size = 512MB`,
      "",
      "# WAL Settings",
      `wal_level = replica`,
      `max_wal_size = 1GB`,
      `min_wal_size = 80MB`,
      `checkpoint_completion_target = 0.9`,
      "",
      "# Query Tuning",
      `random_page_cost = 1.1`,
      `effective_io_concurrency = 0  # 0 on platforms without posix_fadvise`,
      `default_statistics_target = 100`,
      "",
      "# Logging",
      "# One file per weekday, truncated when reused, so data/log holds at most",
      "# a week of logs. Disc also removes files older than that on start.",
      `logging_collector = on`,
      `log_directory = 'log'`,
      LOG_FILENAME,
      LOG_TRUNCATE_ON_ROTATION,
      `log_rotation_age = 1d`,
      LOG_ROTATION_SIZE,
      `log_line_prefix = '%t [%p] %q%u@%d '`,
      LOG_STATEMENT,
      `log_duration = off`,
      `log_min_duration_statement = 100`,
      "",
      "# Error Handling",
      `exit_on_error = off`,
      `restart_after_crash = on`,
      "",
      "# Disc-specific Settings",
      `shared_preload_libraries = ''`,
      `jit = off  # Disable JIT for predictable performance`,
      "",
      "# Locale Settings",
      `datestyle = 'iso, mdy'`,
      `timezone = 'UTC'`,
      `lc_messages = 'en_US.UTF-8'`,
      `lc_monetary = 'en_US.UTF-8'`,
      `lc_numeric = 'en_US.UTF-8'`,
      `lc_time = 'en_US.UTF-8'`,
      `default_text_search_config = 'pg_catalog.english'`
    );

    return lines.join("\n");
  }

  /**
   * Bring a Disc-generated `postgresql.conf` written by an older Disc up to
   * the current logging defaults. `postgresql.conf` is only generated at
   * init, so without this existing instances keep logging every statement
   * into an unbounded number of files. Configs Disc did not generate, and
   * lines the user changed, are returned untouched.
   */
  upgradeLegacyLogging(content: string): string {
    if (!content.startsWith(GENERATED_HEADER))
      return content;

    return content
      .split("\n")
      .map(line => LEGACY_LOGGING_LINES[line] ?? line)
      .join("\n");
  }

  generateHBAConfig(): string {
    const lines: string[] = [
      "# PostgreSQL Client Authentication Configuration",
      "# Generated by Disc",
      "",
      "# TYPE  DATABASE        USER            ADDRESS                 METHOD",
      "",
      "# Local connections via Unix socket",
      "local   all             all                                     trust",
      "",
      "# IPv4 local connections",
      "host    all             all             127.0.0.1/32            trust",
      "",
      "# IPv6 local connections",
      "host    all             all             ::1/128                 trust",
      "",
      "# Disc application connections",
      "local   disc            disc                                    trust",
      "host    disc            disc            127.0.0.1/32            trust"
    ];

    return lines.join("\n");
  }

  generateRecoveryConfig(primaryHost: string, primaryPort: number): string {
    const lines: string[] = [
      "# Recovery configuration for streaming replication",
      `primary_conninfo = 'host=${primaryHost} port=${primaryPort} user=replication'`,
      `primary_slot_name = 'disc_replica_slot'`,
      `recovery_target_timeline = 'latest'`
    ];

    return lines.join("\n");
  }

  tuneForMemory(totalMemoryMB: number): Partial<PostgresConfigOptions> {
    // Basic tuning based on available memory
    // These are conservative settings suitable for development
    const sharedBuffers = Math.min(
      Math.floor(totalMemoryMB * 0.25),
      2048
    );

    const workMem = Math.max(4, Math.floor(totalMemoryMB / 100));

    return {
      maxConnections: totalMemoryMB < 1024 ? 50 : 100,
      sharedBuffers: `${sharedBuffers}MB`,
      workMem: `${workMem}MB`
    };
  }

  validate(_configPath: string): Promise<boolean> {
    // Validate a postgresql.conf file
    // In a real implementation, this would parse and validate the config
    return Promise.resolve(true);
  }
}
