/*** SPDX-License-Identifier: Apache-2.0
     Copyright 2026 Ideas Never Cease ***/

/**
 * PostgreSQL logging defaults.
 *
 * The bug: new instances logged every statement (`log_statement = 'all'`)
 * into uniquely named files rotated at 100 MB with no cap on their number —
 * a day of test runs grew `data/log/` to 19 GB and filled the disk.
 */

import { assertEquals, assertStringIncludes } from "@std/assert";
import { join } from "@std/path";
import { PostgresConfig, pruneStaleLogFiles } from "./config.ts";

const DAY_MS = 24 * 60 * 60 * 1000;

const LEGACY_LOGGING = [
  "# PostgreSQL configuration generated by Disc",
  "",
  "# Logging",
  "logging_collector = on",
  "log_directory = 'log'",
  "log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'",
  "log_rotation_age = 1d",
  "log_rotation_size = 100MB",
  "log_line_prefix = '%t [%p] %q%u@%d '",
  "log_statement = 'all'",
  "log_duration = off"
]
  .join("\n");

function generated(): string {
  return new PostgresConfig().generate({ dataDir: "/tmp/data" });
}

function setting(conf: string, name: string): string | undefined {
  const line = conf.split("\n").find(l => l.startsWith(`${name} = `));
  return line?.slice(name.length + 3).replace(/\s+#.*$/, "");
}

Deno.test("PostgresConfig - logs DDL statements only by default", () => {
  assertEquals(setting(generated(), "log_statement"), "'ddl'");
});

Deno.test("PostgresConfig - log files cycle through one file per weekday", () => {
  assertEquals(setting(generated(), "log_filename"), "'postgresql-%a.log'");
});

Deno.test("PostgresConfig - reused log files are truncated on rotation", () => {
  assertEquals(setting(generated(), "log_truncate_on_rotation"), "on");
});

Deno.test("PostgresConfig - log files rotate daily and never by size", () => {
  const conf = generated();
  assertEquals([setting(conf, "log_rotation_age"), setting(conf, "log_rotation_size")], ["1d", "0"]);
});

Deno.test("PostgresConfig.upgradeLegacyLogging - rewrites Disc's old logging defaults", () => {
  const upgraded = new PostgresConfig().upgradeLegacyLogging(LEGACY_LOGGING);

  assertEquals(
    ["log_filename", "log_rotation_size", "log_statement", "log_truncate_on_rotation"].map(name => setting(upgraded, name)),
    ["'postgresql-%a.log'", "0", "'ddl'", "on"]
  );
});

Deno.test("PostgresConfig.upgradeLegacyLogging - is idempotent", () => {
  const config = new PostgresConfig();
  const once = config.upgradeLegacyLogging(LEGACY_LOGGING);

  assertEquals(config.upgradeLegacyLogging(once), once);
});

Deno.test("PostgresConfig.upgradeLegacyLogging - leaves a freshly generated config unchanged", () => {
  const conf = generated();
  assertEquals(new PostgresConfig().upgradeLegacyLogging(conf), conf);
});

Deno.test("PostgresConfig.upgradeLegacyLogging - keeps settings the user changed", () => {
  const custom = LEGACY_LOGGING.replace("log_statement = 'all'", "log_statement = 'mod'");
  assertStringIncludes(new PostgresConfig().upgradeLegacyLogging(custom), "log_statement = 'mod'");
});

Deno.test("PostgresConfig.upgradeLegacyLogging - ignores configs Disc did not generate", () => {
  const foreign = LEGACY_LOGGING.replace("# PostgreSQL configuration generated by Disc", "# hand-written");
  assertEquals(new PostgresConfig().upgradeLegacyLogging(foreign), foreign);
});

Deno.test("pruneStaleLogFiles - removes PostgreSQL log files last written six or more days ago", async () => {
  const logDir = await Deno.makeTempDir({ prefix: "disc-pg-log-" });
  const now = Date.now();
  const files: Record<string, number> = {
    "notes.txt": now - 30 * DAY_MS,
    "postgresql-2026-09-01_101010.log": now - 25 * DAY_MS,
    "postgresql-Mon.log": now - 6 * DAY_MS - 60_000,
    "postgresql-Sat.log": now - 2 * DAY_MS,
    "postgresql-Sun.log": now - DAY_MS
  };

  try {
    for (const [name, mtime] of Object.entries(files)) {
      const path = join(logDir, name);
      await Deno.writeTextFile(path, "x");
      await Deno.utime(path, mtime / 1000, mtime / 1000);
    }

    await pruneStaleLogFiles(logDir, now);

    const remaining: string[] = [];
    for await (const entry of Deno.readDir(logDir))
      remaining.push(entry.name);

    assertEquals(remaining.sort(), ["notes.txt", "postgresql-Sat.log", "postgresql-Sun.log"]);
  } finally {
    await Deno.remove(logDir, { recursive: true });
  }
});

Deno.test("pruneStaleLogFiles - tolerates a missing log directory", async () => {
  const parent = await Deno.makeTempDir({ prefix: "disc-pg-log-" });

  try {
    await pruneStaleLogFiles(join(parent, "missing"));
  } finally {
    await Deno.remove(parent, { recursive: true });
  }
});
