/*** SPDX-License-Identifier: Apache-2.0
     Copyright 2026 Ideas Never Cease ***/

export interface PostgresConfigOptions {
  dataDir: string;
  maxConnections?: number;
  port?: number;
  sharedBuffers?: string;
  socketDir?: string;
  workMem?: string;
}

export class PostgresConfig {
  generate(options: PostgresConfigOptions): string {
    const {
      maxConnections = 100,
      port = 0,
      sharedBuffers = "128MB",
      socketDir,
      workMem = "4MB"
    } = options;

    const lines: string[] = [
      "# PostgreSQL configuration generated by Disc",
      "# https://github.com/nickel/disc",
      "",
      "# Connection Settings",
      `listen_addresses = ''  # Unix socket only by default`,
      `port = ${port === 0 ? 5432 : port}  # Default port for socket file naming`,
      `max_connections = ${maxConnections}`,
      `superuser_reserved_connections = 3`
    ];

    if (socketDir) {
      lines.push(`unix_socket_directories = '${socketDir}'`);
    }

    lines.push(
      "",
      "# Memory Settings",
      `shared_buffers = ${sharedBuffers}`,
      `work_mem = ${workMem}`,
      `maintenance_work_mem = 64MB`,
      `effective_cache_size = 512MB`,
      "",
      "# WAL Settings",
      `wal_level = replica`,
      `max_wal_size = 1GB`,
      `min_wal_size = 80MB`,
      `checkpoint_completion_target = 0.9`,
      "",
      "# Query Tuning",
      `random_page_cost = 1.1`,
      `effective_io_concurrency = 0  # 0 on platforms without posix_fadvise`,
      `default_statistics_target = 100`,
      "",
      "# Logging",
      `logging_collector = on`,
      `log_directory = 'log'`,
      `log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'`,
      `log_rotation_age = 1d`,
      `log_rotation_size = 100MB`,
      `log_line_prefix = '%t [%p] %q%u@%d '`,
      `log_statement = 'all'`,
      `log_duration = off`,
      `log_min_duration_statement = 100`,
      "",
      "# Error Handling",
      `exit_on_error = off`,
      `restart_after_crash = on`,
      "",
      "# Disc-specific Settings",
      `shared_preload_libraries = ''`,
      `jit = off  # Disable JIT for predictable performance`,
      "",
      "# Locale Settings",
      `datestyle = 'iso, mdy'`,
      `timezone = 'UTC'`,
      `lc_messages = 'en_US.UTF-8'`,
      `lc_monetary = 'en_US.UTF-8'`,
      `lc_numeric = 'en_US.UTF-8'`,
      `lc_time = 'en_US.UTF-8'`,
      `default_text_search_config = 'pg_catalog.english'`
    );

    return lines.join("\n");
  }

  generateHBAConfig(): string {
    const lines: string[] = [
      "# PostgreSQL Client Authentication Configuration",
      "# Generated by Disc",
      "",
      "# TYPE  DATABASE        USER            ADDRESS                 METHOD",
      "",
      "# Local connections via Unix socket",
      "local   all             all                                     trust",
      "",
      "# IPv4 local connections",
      "host    all             all             127.0.0.1/32            trust",
      "",
      "# IPv6 local connections",
      "host    all             all             ::1/128                 trust",
      "",
      "# Disc application connections",
      "local   disc            disc                                    trust",
      "host    disc            disc            127.0.0.1/32            trust"
    ];

    return lines.join("\n");
  }

  generateRecoveryConfig(primaryHost: string, primaryPort: number): string {
    const lines: string[] = [
      "# Recovery configuration for streaming replication",
      `primary_conninfo = 'host=${primaryHost} port=${primaryPort} user=replication'`,
      `primary_slot_name = 'disc_replica_slot'`,
      `recovery_target_timeline = 'latest'`
    ];

    return lines.join("\n");
  }

  tuneForMemory(totalMemoryMB: number): Partial<PostgresConfigOptions> {
    // Basic tuning based on available memory
    // These are conservative settings suitable for development
    const sharedBuffers = Math.min(
      Math.floor(totalMemoryMB * 0.25),
      2048
    );

    const workMem = Math.max(4, Math.floor(totalMemoryMB / 100));

    return {
      maxConnections: totalMemoryMB < 1024 ? 50 : 100,
      sharedBuffers: `${sharedBuffers}MB`,
      workMem: `${workMem}MB`
    };
  }

  validate(_configPath: string): Promise<boolean> {
    // Validate a postgresql.conf file
    // In a real implementation, this would parse and validate the config
    return Promise.resolve(true);
  }
}
