/*** SPDX-License-Identifier: Apache-2.0
     Copyright 2026 Ideas Never Cease ***/

/**
 * Embedded PostgreSQL manifest.
 *
 * Auto-generated by `cli/build.ts` when the build step finds a
 * cached PostgreSQL distribution under `<DISC_HOME>/postgres/<version>/`
 * and `DISC_BUILD_NO_BUNDLE_PG` is unset. Each entry points at a file
 * `deno compile --include` baked into the binary.
 *
 * Default state: empty array. With an empty manifest,
 * `resolveEmbeddedPgBinDir(...)` returns null and the runtime falls
 * back to `PostgresBinaryDownloader` (network download from Maven
 * Central). That keeps `deno task cli` and `deno task build --lite`
 * working without an installed PG distribution.
 *
 * To rebuild the manifest:
 *   1. Run any flow that primes `<DISC_HOME>/postgres/<version>/`
 *      (e.g. `deno task cli init && deno task cli start`).
 *   2. `deno task cli build` regenerates this file before deno compile.
 *   3. The compiled binary now ships PG embedded.
 *
 * The manifest contains absolute `file://` URLs from the build
 * machine, so a regenerated manifest is build-machine-specific —
 * **do not commit a regenerated manifest**. The repo always ships
 * the empty default; the build step recreates the manifest in place
 * just for that build's compile invocation.
 */

import type { EmbeddedPgEntry } from "./embedded-extractor.ts";

export const EMBEDDED_PG_VERSION = "16.4";
export const EMBEDDED_PG_MANIFEST: readonly EmbeddedPgEntry[] = [];
